### ISSUE TITLE
Date fields are imported as PyQt4.Core.Qdate objects

### ISSUE THREAD

**Issue by GoogleCodeExporter** [romain974/qspatialite#24]
```
Hi (bonjour Romain), 

In versions  7.0.2 et 7.0.1, on QGIS 2.2, we can't import correctly date 
fields. They are converted to  PyQt4.Core.Qdate text objects. 
See attached image. 
Quite a severe bug preventing us from using Qspatialite. 

Cheers 
Régis
```

Original issue reported on code.google.com by `regis.ha...@gmail.com` on 20 Mar 2014 at 3:35

Attachments:
- [bug_qspatialite_date.png](https://storage.googleapis.com/google-code-attachments/qspatialite/issue-24/comment-0/bug_qspatialite_date.png)

**Comment by gispoole** [comment]
Hi, I'm having this issue again in QGis 2.14.

I'm using Qspatialite version 7.0.4 in QGis 2.14. We use QSpatialite to save selected polygons from an MSSQL (2008) layer into spatialite databases.

Since Qgis 2.14 we have noticed that any dates held in the SQL table as a date data type are corrupted when the data is imported into a spatialite database through QSpatialite.

Original Data from MSSQL layer within QGis:  ![before_spatialite](https://user-images.githubusercontent.com/31004437/29365169-e6c372da-828d-11e7-94f7-c99e35fd2e11.JPG)

Data after importing into spatialite database using QSpatialite: ![after_spatialite](https://user-images.githubusercontent.com/31004437/29365168-e6a8901e-828d-11e7-8614-2e772bb5e9e8.JPG)

N.B the field name is the data type used to create the table in MSSQL.

I have tried using the DB manager and this fails stating 'Error 5 - creation of fields failed'

We currently have a workaround that involves using QGis 2.8 to import the layer and then opening it through QGis 2.14 to continue editing, this doesn't corrupt the data.

I'd be grateful of any help. Let me know if I need to log a new issue,
Thanks!




see: https://gis.stackexchange.com/questions/251055/qgis-qspatialite-plugin-corrupting-dates-when-importing-layers/251107#251107
